micronaut:
  application:
    name: domaintest
r2dbc:
  datasources:
    default:
      url: r2dbc:pool://localhost:5432/sandbox
      username: sandbox
      password: sandbox
      schema-generate: CREATE_DROP
      dialect: POSTGRES
      db-type: postgres
      options:
        driver: pool
        protocol: postgres
netty:
  default:
    allocator:
      max-order: 3